env:
  es6: true
  browser: true
  commonjs: true

  parserOptions:
    ecmoFeatures:
      jsx: true
    ecmaVersion: 6
    sourceType: module

    plugins: ['react']

    settings:
      react:
        version: '16'